// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xpll_int.h"

extern XPll_int_Config XPll_int_ConfigTable[];

XPll_int_Config *XPll_int_LookupConfig(u16 DeviceId) {
	XPll_int_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XPLL_INT_NUM_INSTANCES; Index++) {
		if (XPll_int_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XPll_int_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XPll_int_Initialize(XPll_int *InstancePtr, u16 DeviceId) {
	XPll_int_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XPll_int_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XPll_int_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

