// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcurrent_ctrl_dq.h"

extern XCurrent_ctrl_dq_Config XCurrent_ctrl_dq_ConfigTable[];

XCurrent_ctrl_dq_Config *XCurrent_ctrl_dq_LookupConfig(u16 DeviceId) {
	XCurrent_ctrl_dq_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCURRENT_CTRL_DQ_NUM_INSTANCES; Index++) {
		if (XCurrent_ctrl_dq_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCurrent_ctrl_dq_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCurrent_ctrl_dq_Initialize(XCurrent_ctrl_dq *InstancePtr, u16 DeviceId) {
	XCurrent_ctrl_dq_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCurrent_ctrl_dq_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCurrent_ctrl_dq_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

