// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCURRENT_CTRL_DQ_H
#define XCURRENT_CTRL_DQ_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xcurrent_ctrl_dq_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XCurrent_ctrl_dq_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XCurrent_ctrl_dq;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XCurrent_ctrl_dq_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XCurrent_ctrl_dq_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XCurrent_ctrl_dq_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XCurrent_ctrl_dq_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XCurrent_ctrl_dq_Initialize(XCurrent_ctrl_dq *InstancePtr, u16 DeviceId);
XCurrent_ctrl_dq_Config* XCurrent_ctrl_dq_LookupConfig(u16 DeviceId);
int XCurrent_ctrl_dq_CfgInitialize(XCurrent_ctrl_dq *InstancePtr, XCurrent_ctrl_dq_Config *ConfigPtr);
#else
int XCurrent_ctrl_dq_Initialize(XCurrent_ctrl_dq *InstancePtr, const char* InstanceName);
int XCurrent_ctrl_dq_Release(XCurrent_ctrl_dq *InstancePtr);
#endif


void XCurrent_ctrl_dq_Set_rstIntN(XCurrent_ctrl_dq *InstancePtr, u32 Data);
u32 XCurrent_ctrl_dq_Get_rstIntN(XCurrent_ctrl_dq *InstancePtr);
void XCurrent_ctrl_dq_Set_ctrlEna(XCurrent_ctrl_dq *InstancePtr, u32 Data);
u32 XCurrent_ctrl_dq_Get_ctrlEna(XCurrent_ctrl_dq *InstancePtr);
void XCurrent_ctrl_dq_Set_params_dref(XCurrent_ctrl_dq *InstancePtr, u32 Data);
u32 XCurrent_ctrl_dq_Get_params_dref(XCurrent_ctrl_dq *InstancePtr);
void XCurrent_ctrl_dq_Set_params_qref(XCurrent_ctrl_dq *InstancePtr, u32 Data);
u32 XCurrent_ctrl_dq_Get_params_qref(XCurrent_ctrl_dq *InstancePtr);
void XCurrent_ctrl_dq_Set_params_Kp(XCurrent_ctrl_dq *InstancePtr, u32 Data);
u32 XCurrent_ctrl_dq_Get_params_Kp(XCurrent_ctrl_dq *InstancePtr);
void XCurrent_ctrl_dq_Set_params_Ki2(XCurrent_ctrl_dq *InstancePtr, u32 Data);
u32 XCurrent_ctrl_dq_Get_params_Ki2(XCurrent_ctrl_dq *InstancePtr);
void XCurrent_ctrl_dq_Set_params_y_max(XCurrent_ctrl_dq *InstancePtr, u32 Data);
u32 XCurrent_ctrl_dq_Get_params_y_max(XCurrent_ctrl_dq *InstancePtr);
void XCurrent_ctrl_dq_Set_params_y_min(XCurrent_ctrl_dq *InstancePtr, u32 Data);
u32 XCurrent_ctrl_dq_Get_params_y_min(XCurrent_ctrl_dq *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
