// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of rstIntN
//        bit 0  - rstIntN[0] (Read/Write)
//        others - reserved
// 0x14 : reserved
// 0x18 : Data signal of ctrlEna
//        bit 0  - ctrlEna[0] (Read/Write)
//        others - reserved
// 0x1c : reserved
// 0x20 : Data signal of params_dref
//        bit 31~0 - params_dref[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of params_qref
//        bit 31~0 - params_qref[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of params_Kp
//        bit 31~0 - params_Kp[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of params_Ki2
//        bit 31~0 - params_Ki2[31:0] (Read/Write)
// 0x3c : reserved
// 0x40 : Data signal of params_y_max
//        bit 31~0 - params_y_max[31:0] (Read/Write)
// 0x44 : reserved
// 0x48 : Data signal of params_y_min
//        bit 31~0 - params_y_min[31:0] (Read/Write)
// 0x4c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XCURRENT_CTRL_DQ_AXILITES_ADDR_RSTINTN_DATA      0x10
#define XCURRENT_CTRL_DQ_AXILITES_BITS_RSTINTN_DATA      1
#define XCURRENT_CTRL_DQ_AXILITES_ADDR_CTRLENA_DATA      0x18
#define XCURRENT_CTRL_DQ_AXILITES_BITS_CTRLENA_DATA      1
#define XCURRENT_CTRL_DQ_AXILITES_ADDR_PARAMS_DREF_DATA  0x20
#define XCURRENT_CTRL_DQ_AXILITES_BITS_PARAMS_DREF_DATA  32
#define XCURRENT_CTRL_DQ_AXILITES_ADDR_PARAMS_QREF_DATA  0x28
#define XCURRENT_CTRL_DQ_AXILITES_BITS_PARAMS_QREF_DATA  32
#define XCURRENT_CTRL_DQ_AXILITES_ADDR_PARAMS_KP_DATA    0x30
#define XCURRENT_CTRL_DQ_AXILITES_BITS_PARAMS_KP_DATA    32
#define XCURRENT_CTRL_DQ_AXILITES_ADDR_PARAMS_KI2_DATA   0x38
#define XCURRENT_CTRL_DQ_AXILITES_BITS_PARAMS_KI2_DATA   32
#define XCURRENT_CTRL_DQ_AXILITES_ADDR_PARAMS_Y_MAX_DATA 0x40
#define XCURRENT_CTRL_DQ_AXILITES_BITS_PARAMS_Y_MAX_DATA 32
#define XCURRENT_CTRL_DQ_AXILITES_ADDR_PARAMS_Y_MIN_DATA 0x48
#define XCURRENT_CTRL_DQ_AXILITES_BITS_PARAMS_Y_MIN_DATA 32

