// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XPLL_INT_H
#define XPLL_INT_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xpll_int_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XPll_int_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XPll_int;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XPll_int_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XPll_int_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XPll_int_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XPll_int_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XPll_int_Initialize(XPll_int *InstancePtr, u16 DeviceId);
XPll_int_Config* XPll_int_LookupConfig(u16 DeviceId);
int XPll_int_CfgInitialize(XPll_int *InstancePtr, XPll_int_Config *ConfigPtr);
#else
int XPll_int_Initialize(XPll_int *InstancePtr, const char* InstanceName);
int XPll_int_Release(XPll_int *InstancePtr);
#endif


void XPll_int_Set_rstIntN_V(XPll_int *InstancePtr, u32 Data);
u32 XPll_int_Get_rstIntN_V(XPll_int *InstancePtr);
void XPll_int_Set_Ki(XPll_int *InstancePtr, u32 Data);
u32 XPll_int_Get_Ki(XPll_int *InstancePtr);
void XPll_int_Set_Kp(XPll_int *InstancePtr, u32 Data);
u32 XPll_int_Get_Kp(XPll_int *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
