// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of rstIntN_V
//        bit 0  - rstIntN_V[0] (Read/Write)
//        others - reserved
// 0x14 : reserved
// 0x18 : Data signal of Ki
//        bit 31~0 - Ki[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of Kp
//        bit 31~0 - Kp[31:0] (Read/Write)
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XPLL_INT_AXILITES_ADDR_RSTINTN_V_DATA 0x10
#define XPLL_INT_AXILITES_BITS_RSTINTN_V_DATA 1
#define XPLL_INT_AXILITES_ADDR_KI_DATA        0x18
#define XPLL_INT_AXILITES_BITS_KI_DATA        32
#define XPLL_INT_AXILITES_ADDR_KP_DATA        0x20
#define XPLL_INT_AXILITES_BITS_KP_DATA        32

