#!/bin/bash -f
# Vivado (TM) v2017.2 (64-bit)
#
# Filename    : top_bd.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Oct 16 21:23:55 +0200 2017
# IP Build 1909766 on Thu Jun 15 19:58:00 MDT 2017 
#
# usage: top_bd.sh [-help]
# usage: top_bd.sh [-lib_map_path]
# usage: top_bd.sh [-noclean_files]
# usage: top_bd.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'top_bd.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm axi_infrastructure_v1_1_0 xil_common_vip_v1_0_0 smartconnect_v1_0 axi_protocol_checker_v1_1_14 axi_vip_v1_0_2 axi_vip_v1_0_1 lib_cdc_v1_0_2 proc_sys_reset_v5_0_11 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_13 fifo_generator_v13_1_4 axi_data_fifo_v2_1_12 axi_crossbar_v2_1_14 blk_mem_gen_v8_3_6 axi_bram_ctrl_v4_0_11 xlslice_v1_0_1 xbip_utils_v3_0_7 c_reg_fd_v12_0_3 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_3 xbip_dsp48_addsub_v3_0_3 xbip_addsub_v3_0_3 c_addsub_v12_0_10 xbip_bram18k_v3_0_3 mult_gen_v12_0_12 axi_utils_v2_0_3 cordic_v6_0_11 xbip_dsp48_multadd_v3_0_3 floating_point_v7_1_4 xlconcat_v2_1_1 axi_protocol_converter_v2_1_13)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "top_bd.sh - Script generated by export_simulation (Vivado v2017.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/top_bd/ipshared/882c/hdl/FSM_controller_core.vhd" \
    "$ref_dir/../../../bd/top_bd/ipshared/882c/hdl/FSM_controller_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/top_bd/ipshared/882c/hdl/FSM_controller_v1_0.vhd" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_fsm_controller_0_0/sim/top_bd_fsm_controller_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_common_vip_v1_0_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl/xil_common_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v1_1_14 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/a1b2/hdl/axi_protocol_checker_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_0_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl/axi_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_0_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_processing_system7_0_0/sim/top_bd_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_11 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5db7/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_rst_ps7_0_100M_0/sim/top_bd_rst_ps7_0_100M_0.vhd" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_scope_concat_0_0/sim/top_bd_scope_concat_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/f9c1/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/55c0/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/ebc2/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_4 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/95b9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/f582/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_xbar_0/sim/top_bd_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/4158/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_0_11 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/9183/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_axi_bram_ctrl_0_0/sim/top_bd_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/bb23/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_xlslice_0_1/sim/top_bd_xlslice_0_1.v" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_blk_mem_gen_0_0/sim/top_bd_blk_mem_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/top_bd/ipshared/38b1/hdl/scope_3ph_core.vhd" \
    "$ref_dir/../../../bd/top_bd/ipshared/38b1/hdl/scope_3ph_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/top_bd/ipshared/38b1/hdl/scope_3ph_v1_0.vhd" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_scope_3ph_0_0/sim/top_bd_scope_3ph_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_7 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/3d01/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_3 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/e1e2/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1e87/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7db8/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/c9c4/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2957/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_10 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/a394/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/403d/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/f0ab/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_3 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/43f5/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cordic_v6_0_11 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5255/hdl/cordic_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_cordic_0_0/sim/top_bd_cordic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/779d/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_4 $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/4a02/hdl/floating_point_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/d238/hdl/vhdl/pll_int.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/d238/hdl/vhdl/pll_int_AXILiteS_s_axi.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/d238/hdl/vhdl/pll_int_fadd_32nsbkb.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/d238/hdl/vhdl/pll_int_fcmp_32nseOg.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/d238/hdl/vhdl/pll_int_fmul_32nscud.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/d238/hdl/vhdl/pll_int_fpext_32ndEe.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/d238/hdl/ip/pll_int_ap_fadd_3_full_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/d238/hdl/ip/pll_int_ap_fcmp_0_no_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/d238/hdl/ip/pll_int_ap_fmul_2_max_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/d238/hdl/ip/pll_int_ap_fpext_0_no_dsp_32.vhd" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_pll_int_0_0/sim/top_bd_pll_int_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_xlslice_cos_0/sim/top_bd_xlslice_cos_0.v" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_xlslice_sin_0/sim/top_bd_xlslice_sin_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/top_bd/hdl/top_bd.vhd" \
    "$ref_dir/../../../bd/top_bd/ipshared/2601/src/adc_interface.vhd" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_adc_interface_0_0/sim/top_bd_adc_interface_0_0.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/bc35/src/PWM_3rdHarm.vhd" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_pwm_3rdharm_0_0/sim/top_bd_pwm_3rdharm_0_0.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2a4f/hdl/vhdl/vsi_control.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2a4f/hdl/vhdl/vsi_control_AXILiteS_s_axi.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2a4f/hdl/vhdl/vsi_control_faddfbkb.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2a4f/hdl/vhdl/vsi_control_fadd_cud.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2a4f/hdl/vhdl/vsi_control_fcmp_fYi.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2a4f/hdl/vhdl/vsi_control_fmul_dEe.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2a4f/hdl/vhdl/vsi_control_sitofeOg.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2a4f/hdl/ip/vsi_control_ap_faddfsub_3_full_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2a4f/hdl/ip/vsi_control_ap_fadd_3_full_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2a4f/hdl/ip/vsi_control_ap_fcmp_0_no_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2a4f/hdl/ip/vsi_control_ap_fmul_2_max_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2a4f/hdl/ip/vsi_control_ap_sitofp_4_no_dsp_32.vhd" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_vsi_control_0_0/sim/top_bd_vsi_control_0_0.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/092f/hdl/vhdl/phase_generator_fbkb.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/092f/hdl/vhdl/phase_generator_fp.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/092f/hdl/vhdl/phase_generator_fp_AXILiteS_s_axi.vhd" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_phase_generator_fp_0_0/sim/top_bd_phase_generator_fp_0_0.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/83ac/hdl/vhdl/dq2alphaBeta2abc.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/83ac/hdl/vhdl/dq2alphaBeta2abc_bkb.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/83ac/hdl/vhdl/dq2alphaBeta2abc_cud.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/83ac/hdl/vhdl/dq2alphaBeta2abc_dEe.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/83ac/hdl/ip/dq2alphaBeta2abc_ap_faddfsub_3_full_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/83ac/hdl/ip/dq2alphaBeta2abc_ap_fmul_2_max_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/83ac/hdl/ip/dq2alphaBeta2abc_ap_sitofp_4_no_dsp_32.vhd" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_dq2alphaBeta2abc_0_0/sim/top_bd_dq2alphaBeta2abc_0_0.vhd" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_pwm_3rdharm_vsi_0/sim/top_bd_pwm_3rdharm_vsi_0.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ba0/hdl/vhdl/current_ctrl_dq.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ba0/hdl/vhdl/current_ctrl_dq_AXILiteS_s_axi.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ba0/hdl/vhdl/current_ctrl_dq_fbkb.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ba0/hdl/vhdl/current_ctrl_dq_fcud.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ba0/hdl/vhdl/current_ctrl_dq_fdEe.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ba0/hdl/ip/current_ctrl_dq_ap_faddfsub_3_full_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ba0/hdl/ip/current_ctrl_dq_ap_fcmp_0_no_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ba0/hdl/ip/current_ctrl_dq_ap_fmul_2_max_dsp_32.vhd" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_current_ctrl_dq_0_1/sim/top_bd_current_ctrl_dq_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/73b7/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_xlconcat_0_0/sim/top_bd_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/vhdl/abc2alphaBeta2dq.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/vhdl/abc2alphaBeta2dq_bkb.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/vhdl/abc2alphaBeta2dq_cud.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/vhdl/abc2alphaBeta2dq_dEe.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/vhdl/abc2alphaBeta2dq_eOg.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/vhdl/abc2alphaBeta2dq_fYi.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/vhdl/abc2alphaBeta2dq_g8j.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/vhdl/getDQ.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/vhdl/getRealValue.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/ip/abc2alphaBeta2dq_ap_faddfsub_3_full_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/ip/abc2alphaBeta2dq_ap_fadd_3_full_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/ip/abc2alphaBeta2dq_ap_fmul_2_max_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/ip/abc2alphaBeta2dq_ap_fpext_0_no_dsp_32.vhd" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/5483/hdl/ip/abc2alphaBeta2dq_ap_sitofp_4_no_dsp_32.vhd" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_abc2alphaBeta2dq_0_2/sim/top_bd_abc2alphaBeta2dq_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/f0ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/2ad9/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/39ca/hdl/verilog" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/6eb1/hdl" +incdir+"$ref_dir/../../../../3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ipshared/1d61/hdl" \
    "$ref_dir/../../../bd/top_bd/ip/top_bd_auto_pc_0/sim/top_bd_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.top_bd xil_defaultlib.glbl -o top_bd_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./top_bd_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./top_bd.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key top_bd_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc top_bd_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./top_bd.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: top_bd.sh [-help]\n\
Usage: top_bd.sh [-lib_map_path]\n\
Usage: top_bd.sh [-reset_run]\n\
Usage: top_bd.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
