// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xphase_generator_fp.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPhase_generator_fp_CfgInitialize(XPhase_generator_fp *InstancePtr, XPhase_generator_fp_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPhase_generator_fp_Set_incr_V(XPhase_generator_fp *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPhase_generator_fp_WriteReg(InstancePtr->Axilites_BaseAddress, XPHASE_GENERATOR_FP_AXILITES_ADDR_INCR_V_DATA, Data);
}

u32 XPhase_generator_fp_Get_incr_V(XPhase_generator_fp *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPhase_generator_fp_ReadReg(InstancePtr->Axilites_BaseAddress, XPHASE_GENERATOR_FP_AXILITES_ADDR_INCR_V_DATA);
    return Data;
}

