# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Projects/PSoC_3ph_f2f/vivado/3ph_f2f_dq_rev1/src/constr/zybo_constr.xdc

# Block Designs: bd/top_bd/top_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd || ORIG_REF_NAME==top_bd}]

# IP: bd/top_bd/ip/top_bd_fsm_controller_0_0/top_bd_fsm_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_fsm_controller_0_0 || ORIG_REF_NAME==top_bd_fsm_controller_0_0}]

# IP: bd/top_bd/ip/top_bd_processing_system7_0_0/top_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_processing_system7_0_0 || ORIG_REF_NAME==top_bd_processing_system7_0_0}]

# IP: bd/top_bd/ip/top_bd_ps7_0_axi_periph_0/top_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==top_bd_ps7_0_axi_periph_0}]

# IP: bd/top_bd/ip/top_bd_rst_ps7_0_100M_0/top_bd_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==top_bd_rst_ps7_0_100M_0}]

# IP: bd/top_bd/ip/top_bd_scope_concat_0_0/top_bd_scope_concat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_scope_concat_0_0 || ORIG_REF_NAME==top_bd_scope_concat_0_0}]

# IP: bd/top_bd/ip/top_bd_xbar_0/top_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_xbar_0 || ORIG_REF_NAME==top_bd_xbar_0}]

# IP: bd/top_bd/ip/top_bd_axi_bram_ctrl_0_0/top_bd_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==top_bd_axi_bram_ctrl_0_0}]

# IP: bd/top_bd/ip/top_bd_xlslice_0_1/top_bd_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_xlslice_0_1 || ORIG_REF_NAME==top_bd_xlslice_0_1}]

# IP: bd/top_bd/ip/top_bd_blk_mem_gen_0_0/top_bd_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_blk_mem_gen_0_0 || ORIG_REF_NAME==top_bd_blk_mem_gen_0_0}]

# IP: bd/top_bd/ip/top_bd_scope_3ph_0_0/top_bd_scope_3ph_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_scope_3ph_0_0 || ORIG_REF_NAME==top_bd_scope_3ph_0_0}]

# IP: bd/top_bd/ip/top_bd_cordic_0_0/top_bd_cordic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_cordic_0_0 || ORIG_REF_NAME==top_bd_cordic_0_0}]

# IP: bd/top_bd/ip/top_bd_pll_int_0_0/top_bd_pll_int_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_pll_int_0_0 || ORIG_REF_NAME==top_bd_pll_int_0_0}]

# IP: bd/top_bd/ip/top_bd_xlslice_cos_0/top_bd_xlslice_cos_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_xlslice_cos_0 || ORIG_REF_NAME==top_bd_xlslice_cos_0}]

# IP: bd/top_bd/ip/top_bd_xlslice_sin_0/top_bd_xlslice_sin_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_xlslice_sin_0 || ORIG_REF_NAME==top_bd_xlslice_sin_0}]

# IP: bd/top_bd/ip/top_bd_adc_interface_0_0/top_bd_adc_interface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_adc_interface_0_0 || ORIG_REF_NAME==top_bd_adc_interface_0_0}]

# IP: bd/top_bd/ip/top_bd_pwm_3rdharm_0_0/top_bd_pwm_3rdharm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_pwm_3rdharm_0_0 || ORIG_REF_NAME==top_bd_pwm_3rdharm_0_0}]

# IP: bd/top_bd/ip/top_bd_vsi_control_0_0/top_bd_vsi_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_vsi_control_0_0 || ORIG_REF_NAME==top_bd_vsi_control_0_0}]

# IP: bd/top_bd/ip/top_bd_phase_generator_fp_0_0/top_bd_phase_generator_fp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_phase_generator_fp_0_0 || ORIG_REF_NAME==top_bd_phase_generator_fp_0_0}]

# IP: bd/top_bd/ip/top_bd_dq2alphaBeta2abc_0_0/top_bd_dq2alphaBeta2abc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_dq2alphaBeta2abc_0_0 || ORIG_REF_NAME==top_bd_dq2alphaBeta2abc_0_0}]

# IP: bd/top_bd/ip/top_bd_pwm_3rdharm_vsi_0/top_bd_pwm_3rdharm_vsi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_pwm_3rdharm_vsi_0 || ORIG_REF_NAME==top_bd_pwm_3rdharm_vsi_0}]

# IP: bd/top_bd/ip/top_bd_current_ctrl_dq_0_1/top_bd_current_ctrl_dq_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_current_ctrl_dq_0_1 || ORIG_REF_NAME==top_bd_current_ctrl_dq_0_1}]

# IP: bd/top_bd/ip/top_bd_xlconcat_0_0/top_bd_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_xlconcat_0_0 || ORIG_REF_NAME==top_bd_xlconcat_0_0}]

# IP: bd/top_bd/ip/top_bd_abc2alphaBeta2dq_0_2/top_bd_abc2alphaBeta2dq_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_abc2alphaBeta2dq_0_2 || ORIG_REF_NAME==top_bd_abc2alphaBeta2dq_0_2}]

# IP: bd/top_bd/ip/top_bd_auto_pc_0/top_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_auto_pc_0 || ORIG_REF_NAME==top_bd_auto_pc_0}]

# XDC: bd/top_bd/top_bd_ooc.xdc
