# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projects/PSoC_3ph_f2f/vivado/3ph_f2f_dq_rev0/3ph_f2f_dq_prj/3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ip/top_bd_phase_generator_0_0/top_bd_phase_generator_0_0.xci
# IP: The module: 'top_bd_phase_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/PSoC_3ph_f2f/vivado/3ph_f2f_dq_rev0/3ph_f2f_dq_prj/3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ip/top_bd_phase_generator_0_0/constraints/phase_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_phase_generator_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Projects/PSoC_3ph_f2f/vivado/3ph_f2f_dq_rev0/3ph_f2f_dq_prj/3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ip/top_bd_phase_generator_0_0/top_bd_phase_generator_0_0.xci
# IP: The module: 'top_bd_phase_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/PSoC_3ph_f2f/vivado/3ph_f2f_dq_rev0/3ph_f2f_dq_prj/3ph_f2f_dq_prj.srcs/sources_1/bd/top_bd/ip/top_bd_phase_generator_0_0/constraints/phase_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_phase_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
