// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XVSI_CONTROL_H
#define XVSI_CONTROL_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xvsi_control_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XVsi_control_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XVsi_control;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XVsi_control_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XVsi_control_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XVsi_control_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XVsi_control_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XVsi_control_Initialize(XVsi_control *InstancePtr, u16 DeviceId);
XVsi_control_Config* XVsi_control_LookupConfig(u16 DeviceId);
int XVsi_control_CfgInitialize(XVsi_control *InstancePtr, XVsi_control_Config *ConfigPtr);
#else
int XVsi_control_Initialize(XVsi_control *InstancePtr, const char* InstanceName);
int XVsi_control_Release(XVsi_control *InstancePtr);
#endif


void XVsi_control_Set_rstIntN(XVsi_control *InstancePtr, u32 Data);
u32 XVsi_control_Get_rstIntN(XVsi_control *InstancePtr);
void XVsi_control_Set_ctrlByp(XVsi_control *InstancePtr, u32 Data);
u32 XVsi_control_Get_ctrlByp(XVsi_control *InstancePtr);
void XVsi_control_Set_params_vRef(XVsi_control *InstancePtr, u32 Data);
u32 XVsi_control_Get_params_vRef(XVsi_control *InstancePtr);
void XVsi_control_Set_params_Kp(XVsi_control *InstancePtr, u32 Data);
u32 XVsi_control_Get_params_Kp(XVsi_control *InstancePtr);
void XVsi_control_Set_params_Ki2(XVsi_control *InstancePtr, u32 Data);
u32 XVsi_control_Get_params_Ki2(XVsi_control *InstancePtr);
void XVsi_control_Set_params_Kd(XVsi_control *InstancePtr, u32 Data);
u32 XVsi_control_Get_params_Kd(XVsi_control *InstancePtr);
void XVsi_control_Set_params_y_max(XVsi_control *InstancePtr, u32 Data);
u32 XVsi_control_Get_params_y_max(XVsi_control *InstancePtr);
void XVsi_control_Set_params_y_min(XVsi_control *InstancePtr, u32 Data);
u32 XVsi_control_Get_params_y_min(XVsi_control *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
